spring.application.name=UrlShortener


spring.datasource.url=jdbc:mysql://localhost:3306/URL_SHORTENER_DB
spring.datasource.username=root
spring.datasource.password=8941

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=2000
